import './globals.css'
import { Inter } from 'next/font/google'


//contexts
import PostContextProvider from '@/context/PostContextProvider'
import UserContextProvider from "@/context/UserContextProvider"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <UserContextProvider>
        <PostContextProvider>
        {children}
        </PostContextProvider>
      </UserContextProvider>
     
        </body>
    </html>
  )
}
